version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.1

workflows:
  version: 2

  # Dev
  Dev_WorkFlow:
    jobs:
      - path-filtering/filter:
          name: check-updated-files

          mapping: |
            service1/.* run-build-service-1-job true

          base-revision: dev
          config-path: .circleci/continue_config.yml
