# version
version: 2.1

# orbs
orbs:
  maven: circleci/maven@1.2.0

# parameters
parameters:
  run-quality-check-job:
    type: boolean
    default: false
  # run-build-service-2-job:
  #   type: boolean
  #   default: false

# #job
# jobs:
#   Quality-Check:
#     docker:
#       # node for image
#       - image: node:16-alpine3.17
#     steps:
#       - checkout
#       - run:
#           name: Code Scan Using Jest
#           command: |
#             npm install
#             npm run test

# workflow
workflows:
  quality-check:
    when: << pipeline.parameters.run-quality-check-job >>
    jobs:
      docker:
        # node for image
        - image: node:16-alpine3.17
      steps:
        - checkout
        - run:
            name: Code Scan Using Jest
            command: |
              npm install 
              npm run test
